language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '8'
script:
  - npm run build
  - npm test
before_deploy:
  - ls -lh data/*.json
  - npm version --no-git-tag-version --force $(npx semver -i minor $(npm info search-flix-locations version))
deploy:
  provider: npm
  on:
    branch: master
    node: 'stable'
  email: 'mail@jannisr.de'
  api_key: ${NPM_KEY}
  skip_cleanup: true
